import { Course, DocumentResource, PreRegistration, Student, Teacher, UserProfile } from '../types';

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 't-1',
    userId: 'user-prof-1',
    nom: 'Viguier',
    prenom: 'Marc',
    email: 'marc.viguier@auberge-dansante.fr',
    telephone: '06 12 34 56 78',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=250',
    disciplines: ['Aïkido Adapté', 'Éveil Martial'],
    diplomes: ['Ceinture Noire 4e Dan Aïkido', 'Brevet d’État Éducateur Sportif', 'Certificat Sport Santé & Handicap'],
    approchePedagogique: 'Privilégie le désamorçage de l’agressivité, la respiration ventrale et la redirection fluide des tensions motrices.',
    disponibilites: ['Mercredi après-midi', 'Samedi matin'],
    actif: true
  },
  {
    id: 't-2',
    userId: 'user-prof-2',
    nom: 'Moreau',
    prenom: 'Camille',
    email: 'camille.moreau@auberge-dansante.fr',
    telephone: '06 23 45 67 89',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    disciplines: ['Judo Éducatif', 'Karaté Do Doux'],
    diplomes: ['Ceinture Noire 3e Dan Judo', 'Diplôme Universitaire Activité Physique Adaptée (APA)', 'Formation Neuro-développement de l’enfant'],
    approchePedagogique: 'Travail au sol sécurisé, apprentissage des chutes sans crainte et renforcement de l’axe corporel.',
    disponibilites: ['Mardi soir', 'Mercredi matin', 'Vendredi soir'],
    actif: true
  },
  {
    id: 't-3',
    userId: 'user-prof-3',
    nom: 'Santos',
    prenom: 'Tiago',
    email: 'tiago.santos@auberge-dansante.fr',
    telephone: '06 34 56 78 90',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    disciplines: ['Capoeira Inclusive'],
    diplomes: ['Contra-Mestre Capoeira', 'Éducateur Spécialisé DEES', 'Musicothérapie appliquée'],
    approchePedagogique: 'L’art du dialogue rythmé par le berimbau, la coordination motrice dans la joie et l’expression corporelle libérée de tout jugement.',
    disponibilites: ['Lundi soir', 'Samedi après-midi'],
    actif: true
  },
  {
    id: 't-4',
    userId: 'user-prof-4',
    nom: 'Lin-Boucher',
    prenom: 'Hélène',
    email: 'helene.lin@auberge-dansante.fr',
    telephone: '06 45 67 89 01',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250',
    disciplines: ['Tai-Chi & Respiration'],
    diplomes: ['Enseignante diplômée Tai-Chi Chuan & Qi Gong', 'Sophrologue certifiée RNCP'],
    approchePedagogique: 'Mouvements lents et continus pour apaiser le système nerveux, travail sur l’attention focalisée et l’enracinement postural.',
    disponibilites: ['Mercredi fin d’après-midi', 'Jeudi soir'],
    actif: true
  }
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'c-1',
    titre: 'Aïkido Doux - Éveil & Confiance',
    discipline: 'Aïkido Adapté',
    jour: 'Mercredi',
    heureDebut: '14:00',
    heureFin: '15:15',
    professeurId: 't-1',
    professeurNom: 'Marc Viguier',
    professeurAvatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=250',
    niveau: 'Initiation (7-10 ans)',
    salle: 'Dojo Principal - Les Bambous',
    capaciteMax: 8,
    inscritsIds: ['s-1', 's-2', 's-3', 's-4'],
    description: 'Séance axée sur l’équilibre, l’esquive bienveillante et la canalisation des émotions fortes à travers des roulades douces et des jeux de partenaire coopératifs.',
    objectifs: [
      'Apprendre à tomber sans se faire mal',
      'Identifier ses tensions musculaires et respirer',
      'Coopérer sans esprit de confrontation'
    ],
    couleurAccent: '#2D5A43'
  },
  {
    id: 'c-2',
    titre: 'Judo Éducatif & Schéma Corporel',
    discipline: 'Judo Éducatif',
    jour: 'Mercredi',
    heureDebut: '10:00',
    heureFin: '11:00',
    professeurId: 't-2',
    professeurNom: 'Camille Moreau',
    professeurAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    niveau: 'Éveil (4-6 ans)',
    salle: 'Dojo Principal - Les Bambous',
    capaciteMax: 6,
    inscritsIds: ['s-5', 's-6'],
    description: 'Petits groupes adaptés aux très jeunes enfants ayant besoin de repères spatiaux, de motricité globale et d’un cadre rassurant et ludique.',
    objectifs: [
      'Reconnaître sa droite, sa gauche et son centre de gravité',
      'Respecter les rituels du salut (Rei)',
      'Développer la motricité fine et l’équilibre'
    ],
    couleurAccent: '#1E3A5F'
  },
  {
    id: 'c-3',
    titre: 'Capoeira Inclusive - Rythme & Agilité',
    discipline: 'Capoeira Inclusive',
    jour: 'Samedi',
    heureDebut: '14:30',
    heureFin: '16:00',
    professeurId: 't-3',
    professeurNom: 'Tiago Santos',
    professeurAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    niveau: 'Ados (11-15 ans)',
    salle: 'Grande Salle Rythmique - Le Chêne',
    capaciteMax: 10,
    inscritsIds: ['s-7', 's-8', 's-9'],
    description: 'Mélange harmonieux de mouvements martiaux, de percussions afro-brésiliennes et d’acrobaties sécurisées. Idéal pour reprendre confiance et s’exprimer sans filtre négatif.',
    objectifs: [
      'Découvrir les instruments de percussion et le chant',
      'Améliorer la souplesse et la coordination motrice',
      'Créer du lien social dans un cercle d’écoute et d’encouragement'
    ],
    couleurAccent: '#8C6D58'
  },
  {
    id: 'c-4',
    titre: 'Tai-Chi Douceur & Sérénité',
    discipline: 'Tai-Chi & Respiration',
    jour: 'Jeudi',
    heureDebut: '17:30',
    heureFin: '18:45',
    professeurId: 't-4',
    professeurNom: 'Hélène Lin-Boucher',
    professeurAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250',
    niveau: 'Tous niveaux',
    salle: 'Espace Sérénité - Les Galets',
    capaciteMax: 8,
    inscritsIds: ['s-1', 's-10'],
    description: 'Pratique lente et profonde visant à diminuer l’anxiété, améliorer la concentration scolaire et réguler les états d’agitation intérieure.',
    objectifs: [
      'Exercices de cohérence cardiaque et d’ancrage',
      'Mémorisation des formes traditionnelles douces',
      'Apaisement sensoriel et relaxation guidée'
    ],
    couleurAccent: '#3D7858'
  },
  {
    id: 'c-5',
    titre: 'Karaté Do Apaisé - Respect & Posture',
    discipline: 'Karaté Do Doux',
    jour: 'Vendredi',
    heureDebut: '18:00',
    heureFin: '19:15',
    professeurId: 't-2',
    professeurNom: 'Camille Moreau',
    professeurAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    niveau: 'Initiation (7-10 ans)',
    salle: 'Dojo Principal - Les Bambous',
    capaciteMax: 8,
    inscritsIds: ['s-2', 's-8'],
    description: 'Karaté traditionnel axé sur le Kata (formes esthétiques) et la maîtrise du geste sans contact agressif. Renforce la structure posturale et la patience.',
    objectifs: [
      'Contrôle millimétré du mouvement sans frappe impulsive',
      'Affirmation de soi mesurée et respect de l’espace d’autrui',
      'Canalisation positive de l’énergie'
    ],
    couleurAccent: '#9B51E0'
  },
  {
    id: 'c-6',
    titre: 'Éveil Martial Sensoriel & Motricité',
    discipline: 'Éveil Martial',
    jour: 'Samedi',
    heureDebut: '10:30',
    heureFin: '11:30',
    professeurId: 't-1',
    professeurNom: 'Marc Viguier',
    professeurAvatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=250',
    niveau: 'Éveil (4-6 ans)',
    salle: 'Espace Éveil Doux - Tatami Vert',
    capaciteMax: 6,
    inscritsIds: ['s-3', 's-5'],
    description: 'Parcours d’obstacles doux, découverte des animaux totem des arts martiaux (le tigre, la grue, la tortue) et jeux d’écoute sensorielle.',
    objectifs: [
      'Découvrir son corps dans l’espace',
      'Apprendre les consignes simples en s’amusant',
      'Partager des moments de joie motrice'
    ],
    couleurAccent: '#D4AF37'
  }
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 's-1',
    nom: 'Martin',
    prenom: 'Léo',
    dateNaissance: '2016-04-12',
    age: 8,
    familleId: 'user-famille-1',
    familleNom: 'Martin',
    familleEmail: 'famille.martin@email.fr',
    familleTelephone: '06 98 76 54 32',
    contactUrgenceNom: 'Sophie Martin (Mère)',
    contactUrgenceTel: '06 98 76 54 32',
    contactUrgenceRelation: 'Mère',
    besoinsSpecifiques: 'Trouble du Déficit de l’Attention (TDAH), grande sensibilité au bruit soudain. A besoin de repères visuels clairs et d’encouragements fréquents.',
    niveauActuel: 'Ceinture Blanche - Barrettes Jaunes (Éveil Confiance)',
    coursInscritsIds: ['c-1', 'c-4'],
    certificatMedical: true,
    dateInscription: '2024-09-05',
    statut: 'actif',
    progression: [
      {
        id: 'p-1',
        date: '2025-01-18',
        discipline: 'Aïkido Adapté',
        competenceCle: 'Roulade avant douce & réception au sol',
        noteEval: 'maitrise',
        commentaireBienveillant: 'Léo a surmonté son appréhension du tatami. Il réalise les roulades avec fluidité et sourit largement à la fin de la série !',
        professeurNom: 'Marc Viguier',
        gradeCeinture: 'Barrette Jaune'
      },
      {
        id: 'p-2',
        date: '2025-02-12',
        discipline: 'Tai-Chi & Respiration',
        competenceCle: 'Postures d’enracinement & Respiration ventrale',
        noteEval: 'acquis',
        commentaireBienveillant: 'Très belle progression sur la posture de l’arbre (Zhan Zhuang). Léo réussit à tenir 3 minutes de calme intérieur.',
        professeurNom: 'Hélène Lin-Boucher'
      }
    ]
  },
  {
    id: 's-2',
    nom: 'Benali',
    prenom: 'Nour',
    dateNaissance: '2015-11-03',
    age: 9,
    familleId: 'user-famille-2',
    familleNom: 'Benali',
    familleEmail: 'karim.benali@email.fr',
    familleTelephone: '06 87 65 43 21',
    contactUrgenceNom: 'Karim Benali (Père)',
    contactUrgenceTel: '06 87 65 43 21',
    contactUrgenceRelation: 'Père',
    besoinsSpecifiques: 'Dyspraxie visuo-spatiale, fatigue musculaire plus rapide. Privilégier les décompositions de mouvements pas-à-pas.',
    niveauActuel: 'Ceinture Blanche - 1er Dan Découverte',
    coursInscritsIds: ['c-1', 'c-5'],
    certificatMedical: true,
    dateInscription: '2024-09-10',
    statut: 'actif',
    progression: [
      {
        id: 'p-3',
        date: '2025-01-25',
        discipline: 'Aïkido Adapté',
        competenceCle: 'Placement des pieds et salut respectueux',
        noteEval: 'acquis',
        commentaireBienveillant: 'Nour fait preuve d’une concentration exemplaire. Sa posture au salut est devenue très stable et assurée.',
        professeurNom: 'Marc Viguier'
      }
    ]
  },
  {
    id: 's-3',
    nom: 'Dubois',
    prenom: 'Arthur',
    dateNaissance: '2019-06-20',
    age: 5,
    familleId: 'user-famille-3',
    familleNom: 'Dubois',
    familleEmail: 'claire.dubois@email.fr',
    familleTelephone: '06 76 54 32 10',
    contactUrgenceNom: 'Claire Dubois (Mère)',
    contactUrgenceTel: '06 76 54 32 10',
    contactUrgenceRelation: 'Mère',
    besoinsSpecifiques: 'Spectre de l’Autisme (TSA léger), hypersensibilité tactile au kimono (port d’un t-shirt en coton autorisé sous la veste).',
    niveauActuel: 'Éveil Petite Salamandre',
    coursInscritsIds: ['c-1', 'c-6'],
    certificatMedical: true,
    dateInscription: '2024-10-02',
    statut: 'actif',
    progression: [
      {
        id: 'p-4',
        date: '2025-02-01',
        discipline: 'Éveil Martial',
        competenceCle: 'Parcours moteur et coordination animale (la Tortue)',
        noteEval: 'acquis',
        commentaireBienveillant: 'Arthur a adoré imiter la posture de la tortue. Il a accepté d’échanger un check complice avec son binôme.',
        professeurNom: 'Marc Viguier'
      }
    ]
  },
  {
    id: 's-4',
    nom: 'Lefebvre',
    prenom: 'Maya',
    dateNaissance: '2016-08-14',
    age: 8,
    familleId: 'user-famille-4',
    familleNom: 'Lefebvre',
    familleEmail: 'elodie.lefebvre@email.fr',
    familleTelephone: '06 65 43 21 09',
    contactUrgenceNom: 'Élodie Lefebvre (Mère)',
    contactUrgenceTel: '06 65 43 21 09',
    contactUrgenceRelation: 'Mère',
    besoinsSpecifiques: 'Anxiété de performance importante, perte de confiance suite à harcèlement scolaire. Grand besoin de validation positive.',
    niveauActuel: 'Ceinture Blanche - 2 barrettes',
    coursInscritsIds: ['c-1'],
    certificatMedical: true,
    dateInscription: '2024-09-12',
    statut: 'actif',
    progression: []
  },
  {
    id: 's-5',
    nom: 'Rousseau',
    prenom: 'Gaspard',
    dateNaissance: '2019-12-01',
    age: 5,
    familleId: 'user-famille-5',
    familleNom: 'Rousseau',
    familleEmail: 'mathieu.rousseau@email.fr',
    familleTelephone: '06 54 32 10 98',
    contactUrgenceNom: 'Mathieu Rousseau (Père)',
    contactUrgenceTel: '06 54 32 10 98',
    contactUrgenceRelation: 'Père',
    besoinsSpecifiques: 'Retard de motricité globale et timidité excessive.',
    niveauActuel: 'Éveil Petit Tigre',
    coursInscritsIds: ['c-2', 'c-6'],
    certificatMedical: true,
    dateInscription: '2024-11-15',
    statut: 'actif',
    progression: []
  },
  {
    id: 's-6',
    nom: 'Diallo',
    prenom: 'Aminata',
    dateNaissance: '2018-03-22',
    age: 6,
    familleId: 'user-famille-6',
    familleNom: 'Diallo',
    familleEmail: 'fatou.diallo@email.fr',
    familleTelephone: '06 43 21 09 87',
    contactUrgenceNom: 'Fatou Diallo (Mère)',
    contactUrgenceTel: '06 43 21 09 87',
    contactUrgenceRelation: 'Mère',
    besoinsSpecifiques: 'Gestion des colères et impulsivité.',
    niveauActuel: 'Ceinture Blanche Judo Éducatif',
    coursInscritsIds: ['c-2'],
    certificatMedical: true,
    dateInscription: '2024-09-08',
    statut: 'actif',
    progression: []
  },
  {
    id: 's-7',
    nom: 'Garnier',
    prenom: 'Lucas',
    dateNaissance: '2011-09-30',
    age: 13,
    familleId: 'user-famille-7',
    familleNom: 'Garnier',
    familleEmail: 'nathalie.garnier@email.fr',
    familleTelephone: '06 32 10 98 76',
    contactUrgenceNom: 'Nathalie Garnier (Mère)',
    contactUrgenceTel: '06 32 10 98 76',
    contactUrgenceRelation: 'Mère',
    besoinsSpecifiques: 'Haut Potentiel Émotionnel, isolement social au collège.',
    niveauActuel: 'Corde Verte Capoeira (Initié)',
    coursInscritsIds: ['c-3'],
    certificatMedical: true,
    dateInscription: '2024-09-01',
    statut: 'actif',
    progression: []
  },
  {
    id: 's-8',
    nom: 'Perez',
    prenom: 'Esteban',
    dateNaissance: '2012-05-18',
    age: 12,
    familleId: 'user-famille-8',
    familleNom: 'Perez',
    familleEmail: 'carmen.perez@email.fr',
    familleTelephone: '06 21 09 87 65',
    contactUrgenceNom: 'Carmen Perez (Mère)',
    contactUrgenceTel: '06 21 09 87 65',
    contactUrgenceRelation: 'Mère',
    besoinsSpecifiques: 'Trouble oppositionnel atténué par le cadre structurant des arts martiaux.',
    niveauActuel: 'Ceinture Jaune Karaté & Capoeira',
    coursInscritsIds: ['c-3', 'c-5'],
    certificatMedical: true,
    dateInscription: '2024-09-04',
    statut: 'actif',
    progression: []
  },
  {
    id: 's-9',
    nom: 'Mercier',
    prenom: 'Jade',
    dateNaissance: '2013-01-15',
    age: 12,
    familleId: 'user-famille-9',
    familleNom: 'Mercier',
    familleEmail: 'alain.mercier@email.fr',
    familleTelephone: '06 10 98 76 54',
    contactUrgenceNom: 'Alain Mercier (Père)',
    contactUrgenceTel: '06 10 98 76 54',
    contactUrgenceRelation: 'Père',
    besoinsSpecifiques: 'Sensibilité auditive, besoin de transitions douces.',
    niveauActuel: 'Initié Capoeira Douce',
    coursInscritsIds: ['c-3'],
    certificatMedical: true,
    dateInscription: '2024-09-18',
    statut: 'actif',
    progression: []
  },
  {
    id: 's-10',
    nom: 'Nguyen',
    prenom: 'Milo',
    dateNaissance: '2017-07-09',
    age: 7,
    familleId: 'user-famille-10',
    familleNom: 'Nguyen',
    familleEmail: 'mai.nguyen@email.fr',
    familleTelephone: '06 09 87 65 43',
    contactUrgenceNom: 'Mai Nguyen (Mère)',
    contactUrgenceTel: '06 09 87 65 43',
    contactUrgenceRelation: 'Mère',
    besoinsSpecifiques: 'Timidité sélective, respiration courte lors des situations inconnues.',
    niveauActuel: 'Découverte Tai-Chi',
    coursInscritsIds: ['c-4'],
    certificatMedical: true,
    dateInscription: '2024-10-10',
    statut: 'actif',
    progression: []
  }
];

export const INITIAL_PRE_REGISTRATIONS: PreRegistration[] = [
  {
    id: 'pr-1',
    enfantNom: 'Bernard',
    enfantPrenom: 'Sasha',
    enfantAge: 8,
    parentNom: 'Bernard',
    parentPrenom: 'Aurélie',
    parentEmail: 'aurelie.bernard@exemple.fr',
    parentTelephone: '06 77 88 99 00',
    coursSouhaiteIds: ['c-1'],
    besoinsParticuliers: 'Sasha est diagnostiqué TDAH et a du mal à canaliser son énergie dans les sports collectifs classiques. Nous cherchons un cadre bienveillant.',
    motivationEtAttentes: 'Apprendre à respirer, se sentir valorisé sans la pression du résultat.',
    contactUrgence: 'Aurélie Bernard - 06 77 88 99 00',
    statut: 'en_attente',
    dateDemande: '2025-02-28',
    notesAdmin: 'Rendez-vous téléphonique d’accueil prévu pour échanger sur la première séance d’essai.'
  },
  {
    id: 'pr-2',
    enfantNom: 'Fontaine',
    enfantPrenom: 'Gabriel',
    enfantAge: 5,
    parentNom: 'Fontaine',
    parentPrenom: 'Nicolas',
    parentEmail: 'nicolas.fontaine@exemple.fr',
    parentTelephone: '06 11 22 33 44',
    coursSouhaiteIds: ['c-2', 'c-6'],
    besoinsParticuliers: 'Retard de langage et difficultés motrices légères.',
    motivationEtAttentes: 'Développer son autonomie motrice et la confiance avec d’autres enfants.',
    contactUrgence: 'Nicolas Fontaine - 06 11 22 33 44',
    statut: 'validee',
    dateDemande: '2025-02-20',
    notesAdmin: 'Dossier validé pour le cours d’Éveil Judo du Mercredi matin.'
  },
  {
    id: 'pr-3',
    enfantNom: 'Colin',
    enfantPrenom: 'Emma',
    enfantAge: 13,
    parentNom: 'Colin',
    parentPrenom: 'Valérie',
    parentEmail: 'valerie.colin@exemple.fr',
    parentTelephone: '06 55 44 33 22',
    coursSouhaiteIds: ['c-3'],
    besoinsParticuliers: 'Grande timidité, phobie scolaire en cours de résolution.',
    motivationEtAttentes: 'Retrouver une dynamique de groupe bienveillante grâce à la musique et au mouvement.',
    contactUrgence: 'Valérie Colin - 06 55 44 33 22',
    statut: 'en_attente',
    dateDemande: '2025-03-01'
  }
];

export const INITIAL_DOCUMENTS: DocumentResource[] = [
  {
    id: 'doc-1',
    titre: 'Le Passeport du Petit Pratiquant - L’Auberge Dansante',
    categorie: 'pedagogique',
    description: 'Livret illustré pour accompagner l’enfant : les valeurs du respect, les rituels du Dojo, le code d’honneur et les étapes d’évolution sans stress.',
    format: 'Guide PDF illustré',
    taille: '3.4 Mo',
    telechargementUrl: '#',
    dateAjout: '2024-09-01',
    publicCible: 'tous'
  },
  {
    id: 'doc-2',
    titre: 'Fiche d’exercices respiratoires & d’ancrage à la maison',
    categorie: 'exercices_maison',
    description: '4 rituels simples de 3 minutes (La vague apaisante, L’arbre aux racines profondes, Le salut de la tortue) pour apaiser les moments de surcharge émotionnelle.',
    format: 'Fiche mémo PDF',
    taille: '1.2 Mo',
    telechargementUrl: '#',
    dateAjout: '2024-10-15',
    publicCible: 'famille'
  },
  {
    id: 'doc-3',
    titre: 'Charte Éthique & Bienveillance de l’Association',
    categorie: 'administratif',
    description: 'Engagements de l’équipe pédagogique, règles de vie du Dojo, respect des rythmes individuels et politique de non-discrimination.',
    format: 'Document officiel PDF',
    taille: '850 Ko',
    telechargementUrl: '#',
    dateAjout: '2024-09-01',
    publicCible: 'tous'
  },
  {
    id: 'doc-4',
    titre: 'Capsule Vidéo : Routine d’échauffement doux et ludique',
    categorie: 'video',
    description: 'Vidéo guidée par Sensei Marc et Camille : 8 minutes pour réveiller les articulations en douceur avec un parent ou en autonomie.',
    format: 'Vidéo HD (1080p)',
    taille: '45 Mo',
    telechargementUrl: '#',
    dateAjout: '2024-11-20',
    publicCible: 'famille'
  },
  {
    id: 'doc-5',
    titre: 'Guide Pédagogique Enseignant : Adaptation Sensorielle & Neurodiversité',
    categorie: 'pedagogique',
    description: 'Ressource professionnelle interne : grille d’observation bienveillante, désescalade des crises d’angoisse, aménagement des consignes motrices.',
    format: 'Manuel Enseignant PDF',
    taille: '5.1 Mo',
    telechargementUrl: '#',
    dateAjout: '2024-09-10',
    publicCible: 'professeur'
  },
  {
    id: 'doc-6',
    titre: 'Attestation d’inscription & Facture acquittée (Modèle vierge)',
    categorie: 'administratif',
    description: 'Document officiel pour prise en charge CE, Pass’Sport ou mutuelle.',
    format: 'Formulaire PDF remplissable',
    taille: '420 Ko',
    telechargementUrl: '#',
    dateAjout: '2024-09-01',
    publicCible: 'famille'
  }
];

export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user-admin-1',
    email: 'direction@auberge-dansante.fr',
    nom: 'Beauchamp',
    prenom: 'Claire',
    role: 'admin',
    telephone: '06 01 02 03 04',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=250',
    bio: 'Fondatrice et directrice de L’Auberge Dansante. Passionnée par le pouvoir réparateur et fédérateur des arts martiaux traditionnels.'
  },
  {
    id: 'user-prof-1',
    email: 'marc.viguier@auberge-dansante.fr',
    nom: 'Viguier',
    prenom: 'Marc',
    role: 'professeur',
    telephone: '06 12 34 56 78',
    avatarUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=250',
    disciplines: ['Aïkido Adapté', 'Éveil Martial'],
    specialites: ['Gestion des émotions', 'Aïkido doux', 'Éveil corporel']
  },
  {
    id: 'user-famille-1',
    email: 'famille.martin@email.fr',
    nom: 'Martin',
    prenom: 'Sophie',
    role: 'famille',
    telephone: '06 98 76 54 32',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    elevesLiesIds: ['s-1'],
    bio: 'Maman de Léo (8 ans), inscrit en Aïkido Adapté et Tai-Chi Douceur.'
  }
];
